# settings 
# @player is a placeholder for player name!
# @product is a placeholder for product name!
# & exists to color the messages 

# MySql connection information
MySQL:
   host: 'database_host'
   password: 'database_password'
   user: 'database_user'
   database: 'database_name'

# time to search for approved purchase (m)
time: 5

# personalized messages
message:
 inventory: "&cYour inventory is full! Unable to deliver your product."

# commands to be executed according to the product
1:
 name: "product_name"
 inventory: false
 message: "&a you received @product!"
 commands:
 - say @player lol!
 - say plugin lol!