# conexao ao banco de dados
MySQL:
  host: ""
  usuario: ""
  senha: ""
  database: ""
  
# configurações de tempo para fazer a busca no mysql!
tempo: 5

# mensagem no chat para todos os players ( nome do jogador vem na frente!)
msg: "§a @player Obrigado por efetua sua compra!"

# produto um
1:
 commands:
 - eco give  @player 1

# produtos dois
2:
 commands:
 - eco give  @player 2
 
3:
 commands:
 - eco give  @player 3
  
4:
 commands:
 - eco give  @player 4
  
5:
 commands:
 - eco give  @player 5

6:
 commands:
 - eco give  @player 6

