#################################################################
 # configuration:
 # https://github.com/sebastianjnuwu/KettraShop
#################################################################

# database connection 
MySQL:
  host: ""
  usuario: ""
  senha: ""
  database: ""

# time settings to do mysql fetch!
tempo: 5

# product id, commands
1:
 commands:
 - dar @player produto 