#################################################################
 # configuration: https://github.com/sebastianjnuwu/KettraShop
#################################################################

# database connection 
MySQL:
  host: ""
  usuario: ""
  senha: ""
  database: ""

# time settings to do mysql fetch!
tempo: 5

# Discord webhook notification (required)
webhook:
       url: ""
       mensagem: ""

# message in chat to the player who made the purchase!
mensagem: ""

# product id, commands
1:
 commands:
 - dar @player produto 
