# settings 

# MySql connection information
MySQL:
   host: ''
   password: ''
   user: ''
   database: ''

# time to search for approved purchase (m)
time: 5

# commands to be executed according to the product
1:
 # inventory: false
 commands:
 - ouro enviar @player 75
 - say @player lol!

2:
 # inventory: false
 commands:
 - ouro enviar @player 3500
 - say @player lol!

3:
 # inventory: false
 commands:
 - ouro enviar @player 10000
 - say @player lol!

4:
 # inventory: false
 commands:
 - ouro enviar @player 15000
 - say @player lol!

5:
 # inventory: false
 commands:
 - ouro enviar @player 20000
 - say @player lol!