########################
 # documentation:
 # configuration: https://github.com/sebastianjnuwu/KettraShop
########################

# conexao ao banco de dados
MySQL:
  host: ""
  usuario: ""
  senha: ""
  database: ""

# configurações de tempo para fazer a busca no mysql!
tempo: 5

# notificação via webhook do discord
webhook:
       url: ""
       mensagem: ""

# mensagem no chat para o jogador que fez a compra!
mensagem: ""

# produto id,commandos
1:
 commands:
 - dar @player produto 
