# conexao ao banco de dados
MySQL:
  host: ""
  usuario: ""
  senha: ""
  database: ""
# configurações de tempo para fazer a busca no mysql!
tempo: 1
# id dos produtos + comandos a serem executados!
1:
  commands:
  - cash add @player 15