name: KettraShop
version: 1.2.7-SNAPSHORT
api-version: 1.18
main: kettraworld.com.Kw
author: sebastianjnuwu 
description: "Delivery of the products compared in the store."
website: https://github.com/sebastianjnuwu/KettraShop
commands:
  kw:
    description: Command used no KettraShop plugin
    usage: /kw <reload|info>