name: "KettraShop"
version: "1.2.8"
api-version: 1.18
main: kettraworld.com.Kw
author: Sebastian Jn (sebastianjnuwu)
description: "Delivery of the products compared in the store..."
commands:
  kw:
    permision: "kw.reload"
    description: "Command used no KettraShop plugin"
    usage: /kw <reload>
