name: KettraShop
version: 1.8-SNAPSHORT
api-version: 1.18
main: io.kettra.plugins.belly.Belly
author: sebastianjnuwu
website: https://github.com/sebastianjnuwu/KettraShop
description: product activation plugin inside minecraft!