name: KettraShop
version: 1.2
api-version: 1.17
main: io.kettra.plugins.belly.Belly
author: sebastianjnuwu
website: https://github.com/sebastianjnuwu/KettraShop
description: product activation plugin inside minecraft!